### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by akatsukilevi** [2000222/Robotic-Arm-IK-in-Unity#1]
First of all, loved the code! Small and useful!
And about it's use, what would be the licensing for it? You can check  "[Choose an open source license](https://choosealicense.com/)" for a easy way to choose a license

Asking because I'm interested on using it on my game, and I want to give proper credits and the license for it(if it is allowed)

**Comment by 2000222** [comment]
Fine, good suggestion. I've added the Apache License 2.0. Have fun with it for your game.

**Comment by akatsukilevi** [comment]
Thank you very much!
